// Dictionnaire de mots
const mots = [
    "chat",
    "chien",
    "maison",
    "arbre",
    "voiture",
    "ordinateur",
    "table",
    "fleur",
    "livre",
    "soleil",
    "pluie",
    "nuage",
    "oiseau",
    "montagne",
    "lac",
    "mer",
    "rivière",
    "étoile",
    "lune",
    "planète",
    "galaxie",
    "univers",
    "pomme",
    "banane",
    "orange",
    "kiwi",
    "fraise",
    "cerise",
    "raisin",
    "pastèque",
    "ananas",
    "poire",
    "abricot",
    "pêche",
    "citron",
    "mandarine",
    "grenade",
    "figue",
    "prune",
    "avion",
    "train",
    "vélo",
    "bateau",
    "bus",
    "tramway",
    "métro",
    "hélicoptère",
    "avion",
    "ballon",
    "bateau",
    "voilier",
    "yacht",
    "scooter",
    "moto",
    "voiture",
    "camion",
    "tracteur",
    "fusée",
    "hélicoptère",
    "astronaute",
    "pilote",
    "conducteur",
    "passager",
    "véhicule",
    "animal",
    "plante",
    "fruit",
    "nourriture",
    "boisson",
    "couleur",
    "forme",
    "taille",
    "poids",
    "âge",
    "temps",
    "espace",
    "musique",
    "film",
    "livre",
    "peinture",
    "sculpture",
    "photographie",
    "théâtre",
    "danse",
    "poésie",
    "roman",
    "conte",
    "essai",
    "biographie",
    "science-fiction",
    "fantasy",
    "mystère",
    "horreur",
    "aventure",
    "drame",
    "comédie",
    "action",
    "romance",
    "thriller",
    "western",
    "documentaire",
    "histoire",
    "géographie",
    "mathématiques",
    "physique",
    "chimie",
    "biologie",
    "astronomie",
    "informatique",
    "robotique",
    "intelligence artificielle",
    "technologie",
    "ingénierie",
    "médecine",
    "psychologie",
    "sociologie",
    "philosophie",
    "religion",
    "spiritualité",
    "politique",
    "économie",
    "santé",
    "environnement",
    "éducation",
    "culture",
    "sport",
    "jeu",
    "voyage",
    "aventure",
    "découverte",
    "exploration",
    "rêve",
    "espoir",
    "amour",
    "amitié",
    "famille",
    "travail",
    "bonheur",
    "joie",
    "paix",
    "harmonie",
    "équilibre",
    "beauté",
    "créativité",
    "expression",
    "liberté",
    "justice",
    "vérité",
    "compassion",
    "altruisme",
    "solidarité",
    "tolérance",
    "respect",
    "humilité",
    "gratitude",
    "courage",
    "persévérance",
    "patience",
    "sagesse",
    "bonté",
    "générosité",
    "honnêteté",
    "intégrité",
    "responsabilité",
    "sérénité",
    "tranquillité",
    "réflexion",
    "contemplation",
    "méditation",
    "silence",
    "communication",
    "écoute",
    "compréhension",
    "empathie",
    "gentillesse",
    "compassion",
    "coopération",
    "collaboration",
    "créativité",
    "innovation",
    "adaptabilité",
    "flexibilité",
    "persévérance",
    "résilience",
    "autonomie",
    "initiative",
    "leadership",
    "organisation",
    "planification",
    "efficacité",
    "efficience",
    "productivité",
    "satisfaction",
    "réussite",
    "accomplissement",
    "épanouissement",
    "équilibre",
    "bien-être",
    "bonheur",
    "joie",
    "amour",
    "paix",
    "harmonie",
    "prospérité",
    "abondance",
    "santé",
    "vitalité",
    "longévité",
    "sagesse",
    "connaissance",
    "sérénité",
    "tranquillité",
    "sérénade",
    "tranquille",
    "sérénité",
    "concentration",
    "focus",
    "immersion",
    "engagement",
    "détermination",
    "dévouement",
    "passion",
    "enthousiasme",
    "énergie",
    "vigueur",
    "force",
    "puissance",
    "courage",
    "détermination",
    "audace",
    "ténacité",
    "fermeté",
    "perseverance",
    "résilience",
    "optimisme",
    "positivité",
    "confiance",
    "estime de soi",
    "assurance",
    "fierté",
    "gratitude",
    "appréciation",
    "reconnaissance",
    "humilité",
    "honnêteté",
    "intégrité",
    "responsabilité",
    "éthique",
    "morale",
    "valeurs",
    "principes",
    "éducation",
    "enseignement",
    "apprentissage",
    "formation",
    "instruction",
    "savoir",
    "compétence",
    "habileté",
    "talent",
    "aptitude",
    "capacité",
    "potentiel",
    "intelligence",
    "créativité",
    "imagination",
    "innovation",
    "invention",
    "découverte",
    "exploration",
    "curiosité",
    "questionnement",
    "réflexion",
    "analyse",
    "synthèse",
    "raisonnement",
    "logique",
    "critique",
    "jugement",
    "discernement",
    "perspective",
    "point de vue",
    "opinion",
    "conviction",
    "croyance",
    "religion",
    "spiritualité",
    "philosophie",
    "science",
    "connaissance",
    "vérité",
    "réalité",
    "perception",
    "interprétation",
    "sens",
    "signification",
    "expression",
    "communication",
    "langage",
    "parole",
    "écriture",
    "lecture",
    "conversation",
    "dialogue",
    "discussion",
    "échange",
    "partage",
    "interaction",
    "relation",
    "connexion",
    "lien",
    "attachement",
    "amour",
    "affection",
    "sympathie",
    "empathie",
    "compassion",
    "gentillesse",
    "générosité",
    "altruisme",
    "solidarité",
    "collaboration",
    "coopération",
    "entraide",
    "soutien",
    "encouragement",
    "réconfort",
    "compréhension",
    "tolérance",
    "acceptation",
    "respect",
    "appréciation",
    "admiration",
    "vénération",
    "culte",
    "adoration",
    "célébration",
    "commémoration",
    "reconnaissance",
    "gratitude",
    "merci",
    "pardon",
    "réconciliation",
    "harmonie",
    "paix",
    "unité",
    "solidarité",
    "intégration",
    "inclusion",
    "diversité",
    "tolérance",
    "respect",
    "justice",
    "égalité",
    "équité",
    "fraternité",
    "liberté",
    "indépendance",
    "autonomie",
    "responsabilité",
    "citoyenneté",
    "engagement",
    "participation",
    "démocratie",
    "gouvernance",
    "administration",
    "autorité",
    "pouvoir",
    "contrôle",
    "influence",
    "leadership",
    "direction",
    "gestion",
    "organisation",
    "planification",
    "coordination",
    "supervision",
    "évaluation",
    "amélioration",
    "optimisation",
    "efficacité",
    "efficience",
    "productivité",
    "performance",
    "résultat",
    "succès",
    "accomplissement",
    "réalisation",
    "progression",
    "croissance",
    "développement",
    "innovation",
    "créativité",
    "adaptabilité",
    "flexibilité",
    "agilité",
    "résilience",
    "anticipation",
    "préparation",
    "planification",
    "stratégie",
    "tactique",
    "opportunité",
    "risque",
    "incertitude",
    "ambiguïté",
    "complexité",
    "doute",
    "conflit",
    "désaccord",
    "contradiction",
    "tension",
    "stress",
    "pression",
    "anxiété",
    "peur",
    "inquiétude",
    "angoisse",
    "dépression",
    "solitude",
    "isolement",
    "rejet",
    "exclusion",
    "discrimination",
    "préjugé",
    "stéréotype",
    "biais",
    "injustice",
    "abus",
    "violence",
    "maltraitance",
    "traumatisme",
    "souffrance",
    "douleur",
    "chagrin",
    "tristesse",
    "déception",
    "regret",
    "remords",
    "culpabilité",
    "honte",
    "embarras",
    "humiliation",
    "colère",
    "rage",
    "frustration",
    "irritation",
    "agacement",
    "contrariété",
    "hostilité",
    "animosité",
    "rancœur",
    "envie",
    "jalousie",
    "ressentiment",
    "amertume",
    "haine",
    "mépris",
    "dégoût",
    "aversion",
    "repulsion",
    "indifférence",
    "apathie",
    "ennui",
    "lassitude",
    "désintérêt",
    "détachement",
    "insensibilité",
    "inertie",
    "passivité",
    "léthargie",
    "indolence",
    "procrastination",
    "oubli",
    "négligence",
    "insouciance",
    "imprudence",
    "paysage",
    "forêt",
    "désert",
    "océan",
    "montagnes",
    "plage",
    "jardin",
    "parc",
    "jungle",
    "savane",
    "prairie",
    "glacier",
    "cascade",
    "grotte",
    "volcan",
    "plaine",
    "colline",
    "falaise",
    "récif",
    "archipel",
    "île",
    "continent",
    "équateur",
    "pôle",
    "horizon",
    "aurore",
    "crépuscule",
    "éclipse",
    "tempête",
    "ouragan",
    "tornade",
    "éclair",
    "tonnerre",
    "arc-en-ciel",
    "brouillard",
    "givre",
    "gelée",
    "neige",
    "froid",
    "chaud",
    "température",
    "humidité",
    "vent",
    "bise",
    "brise",
    "rafale",
    "bourrasque",
    "ouragan",
    "cyclone",
    "tremblement de terre",
    "séisme",
    "tsunami",
    "avalanche",
    "inondation",
    "sécheresse",
    "incendie",
    "éruption",
    "lave",
    "cendres",
    "pollution",
    "déforestation",
    "réchauffement climatique",
    "effet de serre",
    "écologie",
    "biodiversité",
    "conservation",
    "recyclage",
    "développement durable",
    "énergies renouvelables",
    "carbone",
    "oxygène",
    "azote",
    "hydrogène",
    "eau",
    "glace",
    "vapeur",
    "pluie",
    "rosée",
    "rivières",
    "fleuves",
    "océans",
    "lacs",
    "mer",
    "falaise",
    "volcan",
    "sismique",
    "tsunamis",
    "coquillage",
    "étoiles",
    "soleil",
    "lune",
    "planètes",
    "galaxies",
    "comètes",
    "astéroïdes",
    "satellites",
    "espace",
    "cosmos",
    "astronaute",
    "cosmonaute",
    "station spatiale",
    "exploration spatiale",
    "planète",
    "étoiles",
    "lumière",
    "lueur",
    "ombres",
    "obscurité",
    "éclipses",
    "étoile filante",
    "constellation",
    "nébuleuse",
    "voie lactée",
    "système solaire",
    "tempête",
    "orage",
    "tonnerre",
    "éclair",
    "électricité",
    "foudre",
    "rayon",
    "nuage",
    "pluie",
    "goutte",
    "arc-en-ciel",
    "brouillard",
    "brume",
    "fumée",
    "poussière",
    "pollution",
    "smog",
    "atmosphère",
    "oxygène",
    "azote",
    "gaz",
    "polluant",
    "carbone",
    "monoxide",
    "diurne",
    "nocturne",
    "aube",
    "crépuscule",
    "horizon",
    "est",
    "ouest",
    "nord",
    "sud",
    "équateur",
    "tropique",
    "capricorne",
    "cancer",
    "latitude",
    "longitude",
    "méridien",
    "fuseau horaire",
    "saison",
    "printemps",
    "été",
    "automne",
    "hiver",
    "équinoxe",
    "solstice",
    "jour",
    "nuit",
    "aube",
    "crépuscule",
    "horloge",
    "calendrier",
    "mois",
    "semaine",
    "jour",
    "heure",
    "minute",
    "seconde",
    "milliseconde",
    "horloge",
    "montre",
    "réveil",
    "sablier",
    "minuteur",
    "cadran solaire",
    "anneau horaire",
    "temporisateur",
    "machine à remonter le temps",
    "chronomètre",
    "champignon",
    "fleur",
    "plante",
    "arbre",
    "herbe",
    "feuille",
    "branche",
    "tronc",
    "racine",
    "fruit",
    "graine",
    "tige",
    "pétale",
    "pistil",
    "étamine",
    "bourgeon",
    "germe",
    "buisson",
    "rosier",
    "arbuste",
    "maïs",
    "blé",
    "riz",
    "orge",
    "avoine",
    "seigle",
    "sorgho",
    "canne à sucre",
    "bambou",
    "bananier",
    "palmier",
    "cocotier",
    "chêne",
    "érable",
    "sapin",
    "pin",
    "cyprès",
    "cedre",
    "bouleau",
    "peuplier",
    "saule",
    "pommier",
    "cerisier",
    "prunier",
    "pêcher",
    "abricotier",
    "poirier",
    "noyer",
    "amandier",
    "olivier",
    "vigne",
    "manguier",
    "papaye",
    "citronnier",
    "oranger",
    "kiwi",
    "ananas",
    "passiflore",
    "figuier",
    "grenadier",
    "azalée",
    "bégonia",
    "camélia",
    "dahlia",
    "fuchsia",
    "hortensia",
    "iris",
    "jacinthe",
    "lys",
    "marguerite",
    "narcisse",
    "orchidée",
    "pensée",
    "rose",
    "tulipe",
    "bouquet",
    "brin",
    "botanique",
    "flore",
    "florence",
    "jardinage",
    "verger",
    "parterre",
    "plate-bande",
    "jardinière",
    "serre",
    "pépinière",
    "jardinier",
    "paysagiste",
    "horticulteur",
    "herboriste",
    "plante",
    "pousse",
    "croissance",
    "photosynthèse",
    "chlorophylle",
    "racine",
    "tige",
    "feuille",
    "fleur",
    "fruit",
    "graine",
    "pollen",
    "germination",
    "éclosion",
    "fructification",
    "maturité",
    "reproduction",
    "pétales",
    "sépales",
    "étamines",
    "pistils",
    "nectar",
    "parfum",
    "nectarine",
];

let motAffiche = "";
let timer;
let tempsRestant = 10;
let timerRunning = false;
let tailleMot = 1; // Taille du mot actuel
let direction = 1; // Direction de progression de la taille des mots (1 pour augmentation, -1 pour diminution)
let NombreMot = 0;

// Historique des mots saisis
let historiqueMots = [];

// Fonction pour choisir un mot aléatoire de la taille spécifiée
function motAleatoire(taille) {
    const motsFiltres = mots.filter(mot => mot.length === taille);
    if (motsFiltres.length === 0) {
        // Si aucun mot n'est trouvé pour la taille spécifiée, retourne un mot de taille quelconque
        return mots[Math.floor(Math.random() * mots.length)];
    }
    const index = Math.floor(Math.random() * motsFiltres.length);
    return motsFiltres[index];
}

// Fonction pour afficher un mot aléatoire sur la page
function afficherMotAleatoire() {
    motAffiche = motAleatoire(tailleMot);
    const motDiv = document.getElementById("motAleatoire");
    motDiv.textContent = motAffiche;
    document.getElementById("inputMot").style.backgroundColor = "var(--bleuMoyen)";
}

// Fonction pour vérifier le mot saisi à chaque frappe
function verifierMotSurFrappes() {
    document.getElementById("inputMot").style.backgroundColor = "var(--bleuMoyen)";
    const motSaisi = document.getElementById("inputMot").value.trim().toLowerCase();

    if (motSaisi === motAffiche) {
        document.getElementById("inputMot").value = ""; // Efface le champ de saisie
        historiqueMots.push({mot: motSaisi, taille: motSaisi.length}); // Ajoute le mot et la taille à l'historique
        tailleMot += direction; // Augmente ou diminue la taille du mot pour le prochain mot
        gererDirection(); // Vérifie et gère la direction de progression
        tempsRestant = 10; // Réinitialise le timer à 10 secondes
        afficherMotAleatoire(); // Affiche un nouveau mot
        NombreMot++;
        console.log(NombreMot);
        document.getElementById("effectNumber").innerText = NombreMot;
        document.getElementById("effectNumber").classList.add("active");
        setTimeout(function(){
            document.getElementById("effectNumber").classList.remove("active");
        }, 600);
        document.getElementById("inputMot").style.backgroundColor = "#00a4ff";
        if (!timerRunning) startTimer(); // Si le timer n'est pas déjà en cours, démarre le timer
    } else if (motAffiche.startsWith(motSaisi)) {
        // Le mot saisi est une sous-chaîne du mot affiché, donc c'est correct
    } else {
        // Le mot saisi est incorrect, donc déduit une seconde du temps restant
        tempsRestant--;
        document.getElementById("inputMot").style.backgroundColor = "red";
        document.getElementById("timer").textContent = "Temps restant : " + tempsRestant + " secondes";
    }
}

// Fonction pour démarrer le timer
function startTimer() {
    timer = setInterval(decrementerTimer, 100);
    timerRunning = true;
}

// Fonction pour décrémenter le timer
function decrementerTimer() {
    if (tempsRestant > 0) {
        tempsRestant -= 0.1;
        document.getElementById("timer").textContent = "Temps restant : " + tempsRestant.toFixed(1) + " secondes";
    } else {
        clearInterval(timer);
        timerRunning = false;
        document.getElementById("finJeu").textContent = "Temps écoulé. Vous avez perdu.";
        document.getElementById("inputMot").disabled = true;
        arreterJeu()
    }
}

// Fonction pour démarrer le jeu
function demarrerJeu() {
    document.getElementById("ecranDemarrage").style.display = "none";
    document.getElementById("jeu").style.display = "block";
    afficherMotAleatoire();
    document.getElementById("inputMot").focus(); // Déplacer le focus sur l'input
    startTimer();
}


// Gestion de l'événement pour vérifier le mot à chaque frappe
document.getElementById("inputMot").addEventListener("input", verifierMotSurFrappes);

// Au chargement de la page, afficher un mot aléatoire
window.onload = function() {
    afficherMotAleatoire();
};

// Mise à jour de l'historique des mots saisis
function mettreAJourHistorique() {
    const historiqueListe = document.getElementById("historiqueMots");
    historiqueListe.innerHTML = ""; // Efface l'historique actuel
    historiqueMots.forEach(item => {
        const li = document.createElement("li");
        const mot = item.mot + " - Taille : " + item.taille;
        li.textContent = mot;
        historiqueListe.appendChild(li);
    });
}

// Mettre à jour l'historique après chaque saisie correcte
setInterval(mettreAJourHistorique, 100);

// Gérer le changement de direction de progression des mots
function gererDirection() {
    if (tailleMot <= 1) {
        direction = 1; // Si la taille du mot est égale ou inférieure à 1, changer la direction pour augmenter la taille
    } else if (tailleMot >= 5) {
        direction = -1; // Si la taille du mot est égale ou supérieure à 5, changer la direction pour diminuer la taille
    }
}


// Fonction pour mettre à jour la largeur de la div "couldown" en fonction du temps restant
function mettreAJourCouldown() {
    const pourcentageRestant = (tempsRestant / 10) * 100; // Calcul du pourcentage de temps restant par rapport au temps initial (10 secondes)
    const couldownDiv = document.getElementById("couldown");
    couldownDiv.style.width = pourcentageRestant + "vw";
}

// Appel de la fonction pour mettre à jour le couldown au chargement de la page et à chaque fois que le timer est décrémenté
window.onload = function() {
    mettreAJourCouldown();
    setInterval(mettreAJourCouldown, 10);
}

// Fonction pour afficher l'écran de game over
function afficherGameOver() {
    document.getElementById("jeu").style.display = "none";
    document.getElementById("gameOver").style.display = "flex";
    document.getElementById("nombreMots").textContent = NombreMot;
    mettreAJourHistoriqueGameOver();
}

// Fonction pour mettre à jour l'historique des mots dans l'écran de game over
function mettreAJourHistoriqueGameOver() {
    const historiqueListeGameOver = document.getElementById("historiqueGameOver");
    historiqueListeGameOver.innerHTML = ""; // Efface l'historique actuel
    historiqueMots.forEach(item => {
        const li = document.createElement("li");
        const mot = item.mot + " - Taille : " + item.taille;
        li.textContent = mot;
        historiqueListeGameOver.appendChild(li);
    });
}

// Gestion de l'événement pour recommencer le jeu
document.getElementById("restart").addEventListener("click", function(){
    window.location.reload();
});

// Fonction pour arrêter le jeu
function arreterJeu() {
    clearInterval(timer);
    afficherGameOver(); // Afficher l'écran de game over
    document.getElementById("inputMot").disabled = true;
}

